---
title: "treeSimulations.Rmd"
author: "April Wright"
date: "2023-03-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(FossilSim)
rate=2



trees <- sim.fbd.taxa(n = 25, numbsim = 5, lambda = 5, mu = 3, psi = 2)
f = sim.fossils.poisson(rate = rate, tree = trees[[1]])  
plot(f, tree = trees[[1]])

```

```{r}

# Load necessary libraries
library(FossilSim)
library(ape)

rate <- 2

# Simulate trees
trees <- sim.fbd.taxa(n = 10, numbsim = 5, lambda = 5, mu = 3, psi = 2)


tree <- trees[[1]]

f <- sim.fossils.poisson(rate = rate, tree = tree)

my_dir <- "~/Desktop/test"
i <- 1
my_file <- file.path(my_dir, paste0("tree_", i, ".nex"))

if (!dir.exists(my_dir)) {
  dir.create(my_dir)
}

tree_ape <- read.tree(text = write.tree(tree))

write.nexus(tree_ape, file = my_file)

plot(f, tree = tree)


```

```{r}

library(FossilSim)
library(ape)
rate=2

nTips = c(10, 10, 10, 10, 25, 25, 25, 25, 50, 50, 50, 50)
Mu = c(1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4)
my_dir_base <- "."
values <- data.frame(nTips, Mu)
i <- 1
for(row in 1:nrow(values)){
  n = values[row, "nTips"]
  mu = values[row, "Mu"]
  trees <- sim.fbd.taxa(n = n, numbsim = 100, lambda = 5, mu = mu, psi = 2)
  i <- 1
  my_dir <- paste0(my_dir_base, "/MU_", n, "_", mu)
  if (!dir.exists(my_dir)) {
  dir.create(my_dir)
  }
  for(tree in trees){
    
    my_file <- file.path(my_dir, paste0("tree_", i, ".nex"))

    f = sim.fossils.poisson(rate = rate, tree = tree)

    tree_ape <- read.tree(text = write.tree(tree))
    
    write.nexus(tree_ape, file = my_file)
    
    
    #plot(f, tree = tree)
    #print(nrow(f))
    i <- i + 1
  }
  
  
 
 # plot(f, tree = trees[[1]])
 # print(paste(n, mu, n+mu))
}


#trees <- sim.fbd.taxa(n = 10, numbsim = 100, lambda = 5, mu = 3, psi = 5)
#f = sim.fossils.poisson(rate = rate, tree = trees[[1]])  
#plot(f, tree = trees[[1]])




```



| Number of Tips | Lambda          | Mu             |
|----------------|-----------------|----------------|
| 10             | 5               | 1              |
| 10             | 5               | 2              |
| 10             | 5               | 3              |
| 10             | 5               | 4              |
| 25             | 5               | 1              |
| 25             | 5               | 2              |
| 25             | 5               | 3              |
| 25             | 5               | 4              |
| 50             | 5               | 1              |
| 50             | 5               | 2              |
| 50             | 5               | 3              |
| 50             | 5               | 4              |
